/** Representative ticket data used to preview templates in the gallery. */
export const sampleCoupleTicket = {
  id: 'SAMPLE-0001',
  reservation_id: 'SAMPLE-RES',
  qr_token: 'ELITE-SAMPLE-COUPLE-0001',
  status: 'ISSUED',
  issued_at: new Date().toISOString(),
  checked_in_at: null,
  event_id: 'sample',
  event_name: 'Annual Charity Gala',
  start_time: '2026-09-12T18:30:00.000Z',
  end_time: '2026-09-12T23:30:00.000Z',
  invitee_name: 'Jane & John Doe',
  room_number: 'A',
  floor_number: 2,
  table_number: '12',
  chair_number: '3',
  reservation_type: 'COUPLE',
  paired_table_number: '12',
  paired_chair_number: '4',
  sessions: [
    { label: 'Church ceremony', datetime: '2026-09-12T11:00:00.000Z', location: 'Koto, St Francis of Assisi Parish' },
    { label: 'Evening reception', datetime: '2026-09-12T19:00:00.000Z', location: 'Bonamoussadi, Dakota Party Hall' },
  ],
};

export const sampleSingleTicket = {
  id: 'SAMPLE-0002',
  reservation_id: 'SAMPLE-RES-2',
  qr_token: 'ELITE-SAMPLE-SINGLE-0002',
  status: 'ISSUED',
  issued_at: new Date().toISOString(),
  checked_in_at: null,
  event_id: 'sample',
  event_name: 'Annual Charity Gala',
  start_time: '2026-09-12T18:30:00.000Z',
  end_time: '2026-09-12T23:30:00.000Z',
  invitee_name: 'Alex Morgan',
  room_number: 'B',
  floor_number: 1,
  table_number: '7',
  chair_number: '2',
  reservation_type: 'SINGLE',
  paired_table_number: '',
  paired_chair_number: '',
  sessions: [
    { label: 'Church ceremony', datetime: '2026-09-12T11:00:00.000Z', location: 'Koto, St Francis of Assisi Parish' },
    { label: 'Evening reception', datetime: '2026-09-12T19:00:00.000Z', location: 'Bonamoussadi, Dakota Party Hall' },
  ],
};
